GameStore/Controllers/CartController.cs
using GameStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GameStore.Controllers
{
    public class CartController : Controller
    {
        public CartContext cartContext;

        public CartController(CartContext cartContext)
        {
            this.cartContext = cartContext;
        }

        
        public async Task<IActionResult> Index(long? id)
        {
            if (id != null)
            {
                return View(await cartContext.CartProducts.FindAsync(id));
            }
            else
            {
                return RedirectToAction(nameof(Home));

            }
        }

        [HttpPost]
        public async Task<IActionResult> Home(long id)
        {
            var cart = await cartContext.CartProducts.FindAsync(id);

            if (cart != null)
            {
                cartContext.CartProducts.Remove(cart);
                await cartContext.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Cart()
        {
            return View();
        }

        public IActionResult Home()
        {
            var cartProducts = cartContext.CartProducts.ToList();
            return View(cartProducts);
        }
    }
}

GameStore/Controllers/StoreController.cs
using GameStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace GameStore.Controllers
{
    public class StoreController : Controller
    {
        public ProductContext productContext;
        public CartContext cartContext;

        public StoreController(ProductContext productContext, CartContext cartContext)
        {
            this.productContext = productContext;
            this.cartContext = cartContext;
        }


        public async Task<IActionResult> Index(long? id)
        {
            if (id != null)
            {
                return View(await productContext.Products.FindAsync(id));
            }
            else
            {
                return RedirectToAction(nameof(Home));
                
            }
        }

        // AddProduct Post
        [HttpPost]
        public async Task<IActionResult> AddProduct(Product product)
        {
            // only admin can add product
            var currentUserEmail = HttpContext.Session.GetString("CurrentUserEmail");

            if (currentUserEmail != "admin@admin.com")
            {
                return RedirectToAction(nameof(Home));
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var productExist = await productContext.Products.FirstOrDefaultAsync(u => u.Name == product.Name);
                    if (productExist == null)
                    {
                        productContext.Products.Add(product);
                        await productContext.SaveChangesAsync();
                        // redirect login
                        return RedirectToAction(nameof(Home));
                    }
                    else
                    {
                        return RedirectToAction(nameof(AddProduct));
                    }
                }
            }
                return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Index(Cart cart)
        {
            var cartProductExist = await cartContext.CartProducts.FirstOrDefaultAsync(u => u.Name == cart.Name);
                if (cartProductExist == null)
                {
                    cartContext.CartProducts.Add(cart);
                    await cartContext.SaveChangesAsync();

        
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            return View(cart);

        }


        public IActionResult Store()
        {
            return View();
        }

        public IActionResult Home()
        {
            var products = productContext.Products.ToList();
            return View(products);
        }

        public IActionResult AddProduct()
        {
            return View();
        }
    }
}

GameStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Home">Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Home">Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="AddProduct">Add Product(Only Admin)</a>
                        </li>
                    </ul>
                </div>
               

                <div>
                    <ul class="navbar-nav flex-grow-1 ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav flex-grow-1 ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Exit">Exit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>